### ISSUE TITLE
Display won't render certain digits

### ISSUE THREAD

**Issue by KorvinSzanto** [almindor/max7219#5]
My 7seg display (5461as) is acting odd when I try to certain characters. It works fine in many situations but in others it simply lights up all segments full brightness as if in test mode. 

For example it will render the string `b"spi_help"` (though it outputs as "PLEH" on my 4 digit display) but it won't render `b"spi_pleh"` for some reason. Another example is it will render `b"        1"` through 5 fine (7 leading spaces) , but 6 is `8.8.8.8` at fully brightness.

**Comment by KorvinSzanto** [comment]
I think I have things working now that I've switched to `::from_spi_cs(...)` instead of `::from_spi(...)`. I was using a pico and setting all pins to SPI mode but things only work right when I set the cs pin to push_pull_output and pass it in to the `::from_spi_cs` method.

**Comment by almindor** [comment]
heh glad this got resolved :)
